site_name: JavascriptTutorial
pages:
- "Home": 'index.md'
- "Basic":
  - "101": '101.md'
  - "Syntax":
     - "201": '201.md'
     - "Function": 'data_function.md'
  - "Data Structure":
     - "Value, Type, and Operator": 'data_value_type_operator.md'
     - "String": 'data_string.md'
     - "Time": 'data_time.md'
     - "Object": 'data_object.md'
  - "OOP": "oop.md"
  - "Networking": "networking.md"
- "Intermediate":
  - "Logging": "logging.md"
  - "Documentation": "documentation.md"
  - "Testing": "testing.md"
- "Advanced":
  - "Package Manager": "package_manager.md"
  - "Build Tool": "build_tool.md"
  - "Make Module": "make_module.md"
markdown_extensions:
    - footnotes