site_name: JavascriptTutorial
pages:
- "Home": 'index.md'
- "Basic":
  - "101": '101.md'
  - "Syntax": '201.md'
  - "Data Structure":
     - "Number": 'data_number.md'
     - "String": 'data_string.md'
     - "Boolean": 'data_boolean.md'
     - "Time": 'data_time.md'
     - "Object": 'data_object.md'
     - "Array": 'data_array.md'
  - "OOP": "oop.md"
  - "Networking": "networking.md"
- "Intermediate":
  - "Logging": "logging.md"
  - "Documentation": "documentation.md"
  - "Error Handling": "error_handling.md"
  - "Testing": "testing.md"
- "Advanced":
  - "Package Manager": "package_manager.md"
  - "Build Tool": "build_tool.md"
  - "Make Module": "make_module.md"
markdown_extensions:
    - footnotes